@node
@author=Morpheus (perseids-tools)
@convertedBy=Tony Jurg
@coreData=Nestle 1904 Text-Fabric (centerBLC)
@coreDataUrl=https://github.com/CenterBLC/N1904
@description=Morpheus summary group 9: list of morph tags
@license=Creative Commons Attribution 4.0 International (CC BY 4.0)
@licenseUrl=https://github.com/tonyjurg/N1904addons/blob/main/LICENSE.md
@provenance=jupyter Notebook (https://github.com/tonyjurg/create_TF_feature_betacode)
@valueType=str
@version=1.0.0
@website=https://github.com/tonyjurg/N1904addon
@writtenBy=Text-Fabric
@dateWritten=2025-06-05T14:37:34+00:00Z

2937	N-PRI/N-NPN/N-VPN/N-APN/N-NDF/N-VDF/N-ADF/N-NSF/N-VSF
4399	N-PRI/N-NPN/N-VPN/N-APN/N-NDF/N-VDF/N-ADF/N-NSF/N-VSF
4448	N-PRI/N-NPN/N-VPN/N-APN/N-NDF/N-VDF/N-ADF/N-NSF/N-VSF
6561	N-PRI/N-NPN/N-VPN/N-APN/N-NDF/N-VDF/N-ADF/N-NSF/N-VSF
6814	V-PAM-3P/V-PAM-3D
7121	N-PRI/N-NPN/N-VPN/N-APN/N-NDF/N-VDF/N-ADF/N-NSF/N-VSF
7929	N-PRI/N-NPN/N-VPN/N-APN/N-NDF/N-VDF/N-ADF/N-NSF/N-VSF
8626	N-PRI/N-NPN/N-VPN/N-APN/N-NDF/N-VDF/N-ADF/N-NSF/N-VSF
8649	N-PRI/N-NPN/N-VPN/N-APN/N-NDF/N-VDF/N-ADF/N-NSF/N-VSF
10081	N-PRI/N-NPN/N-VPN/N-APN/N-NDF/N-VDF/N-ADF/N-NSF/N-VSF
10092	N-PRI/N-NPN/N-VPN/N-APN/N-NDF/N-VDF/N-ADF/N-NSF/N-VSF
10701	N-PRI/N-NPN/N-VPN/N-APN/N-NDF/N-VDF/N-ADF/N-NSF/N-VSF
11994	V-PAN/V-PAP-VSM/V-PAP-NSN/V-PAP-VSN/V-PAP-ASN/V-PAP-NSM
12462	N-PRI/N-NPN/N-VPN/N-APN/N-NDF/N-VDF/N-ADF/N-NSF/N-VSF
14204	V-PAN/V-PAP-VSM/V-PAP-NSN/V-PAP-VSN/V-PAP-ASN/V-PAP-NSM
16185	V-PAN/V-PAP-VSM/V-PAP-NSN/V-PAP-VSN/V-PAP-ASN/V-PAP-NSM
19319	N-PRI/N-NPN/N-VPN/N-APN/N-NDF/N-VDF/N-ADF/N-NSF/N-VSF
22526	N-PRI/N-NPN/N-VPN/N-APN/N-NDF/N-VDF/N-ADF/N-NSF/N-VSF
22909	N-PRI/N-NPN/N-VPN/N-APN/N-NDF/N-VDF/N-ADF/N-NSF/N-VSF
25434	V-PAN/V-PAP-VSM/V-PAP-NSN/V-PAP-VSN/V-PAP-ASN/V-PAP-NSM
25941	N-PRI/N-NPN/N-VPN/N-APN/N-NDF/N-VDF/N-ADF/N-NSF/N-VSF
26821	V-PAN/V-PAP-VSM/V-PAP-NSN/V-PAP-VSN/V-PAP-ASN/V-PAP-NSM
27825	V-PAN/V-PAP-VSM/V-PAP-NSN/V-PAP-VSN/V-PAP-ASN/V-PAP-NSM
33543	N-PRI/N-NPN/N-VPN/N-APN/N-NDF/N-VDF/N-ADF/N-NSF/N-VSF
39101	V-PAM-3P/V-PAM-3D
39909	N-PRI/N-NPN/N-VPN/N-APN/N-NDF/N-VDF/N-ADF/N-NSF/N-VSF
44695	V-PAN/V-PAP-VSM/V-PAP-NSN/V-PAP-VSN/V-PAP-ASN/V-PAP-NSM
44727	N-PRI/N-NPN/N-VPN/N-APN/N-NDF/N-VDF/N-ADF/N-NSF/N-VSF
44807	V-PAN/V-PAP-VSM/V-PAP-NSN/V-PAP-VSN/V-PAP-ASN/V-PAP-NSM
45079	N-PRI/N-NPN/N-VPN/N-APN/N-NDF/N-VDF/N-ADF/N-NSF/N-VSF
46274	V-PAN/V-PAP-VSM/V-PAP-NSN/V-PAP-VSN/V-PAP-ASN/V-PAP-NSM
46880	V-PAN/V-PAP-VSM/V-PAP-NSN/V-PAP-VSN/V-PAP-ASN/V-PAP-NSM
53834	N-PRI/N-NPN/N-VPN/N-APN/N-NDF/N-VDF/N-ADF/N-NSF/N-VSF
54688	N-PRI/N-NPN/N-VPN/N-APN/N-NDF/N-VDF/N-ADF/N-NSF/N-VSF
57041	V-PPI-3P
58292	N-PRI/N-NPN/N-VPN/N-APN/N-NDF/N-VDF/N-ADF/N-NSF/N-VSF
67398	N-PRI/N-NPN/N-VPN/N-APN/N-NDF/N-VDF/N-ADF/N-NSF/N-VSF
69860	N-NDF/N-VDF/N-ADF/N-NSF/N-VSF
71970	N-NDF/N-VDF/N-ADF/N-NSF/N-VSF
73804	PREP
75112	V-PAI-2S
83486	N-PRI/N-NPN/N-VPN/N-APN/N-NDF/N-VDF/N-ADF/N-NSF/N-VSF
84722	N-PRI/N-NPN/N-VPN/N-APN/N-NDF/N-VDF/N-ADF/N-NSF/N-VSF
85074	N-PRI/N-NPN/N-VPN/N-APN/N-NDF/N-VDF/N-ADF/N-NSF/N-VSF
85238	N-NDF/N-VDF/N-ADF/N-NSF/N-VSF
86363	N-NDF/N-VDF/N-ADF/N-NSF/N-VSF
89336	N-PRI/N-NPN/N-VPN/N-APN/N-NDF/N-VDF/N-ADF/N-NSF/N-VSF
91556	N-PRI/N-NPN/N-VPN/N-APN/N-NDF/N-VDF/N-ADF/N-NSF/N-VSF
94605	V-PAP-NSM
98057	N-PRI/N-NPN/N-VPN/N-APN/N-NDF/N-VDF/N-ADF/N-NSF/N-VSF
101385	N-PRI/N-NPN/N-VPN/N-APN/N-NDF/N-VDF/N-ADF/N-NSF/N-VSF
103548	N-NDF/N-VDF/N-ADF/N-NSF/N-VSF
103918	N-PRI/N-NPN/N-VPN/N-APN/N-NDF/N-VDF/N-ADF/N-NSF/N-VSF
107865	N-PRI/N-NPN/N-VPN/N-APN/N-NDF/N-VDF/N-ADF/N-NSF/N-VSF
109819	V-PAP-NSM
111278	N-NDF/N-VDF/N-ADF/N-NSF/N-VSF
115679	N-PRI/N-NPN/N-VPN/N-APN/N-NDF/N-VDF/N-ADF/N-NSF/N-VSF
123748	N-PRI/N-NPN/N-VPN/N-APN/N-NDF/N-VDF/N-ADF/N-NSF/N-VSF
134881	N-PRI/N-NPN/N-VPN/N-APN/N-NDF/N-VDF/N-ADF/N-NSF/N-VSF
