remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
- jekyll-sitemap

title: N1904addons
description: Additional features for the N1904-TF, the syntactic annotated Text-Fabric dataset of the Greek New Testament.
show_downloads: false
